CREATE TABLE driver
(
    id            int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          varchar(100) NOT NULL,
    sur_name      varchar(100) NOT NULL,
    nick_name     varchar(100) NOT NULL UNIQUE,
    year_of_birth int          NOT NULL
)
GO